### ISSUE TITLE
Error in PDF output - math and \texttt do not render

### ISSUE THREAD

**Issue by jessica0xdata** [GitbookIO/gitbook-pdf#18]
Running into a PDF output error when I click the PDF link (/download/pdf/book). When using the mathjax plugin, everything looks ok online, but the math does not render in the PDF output. Neither does anything using \texttt, although that shows up online as well. EPUB output is also incorrect. Code examples show up in the output fine, however.

**Comment by TomasKulhanek** [comment]
I've recently installed "katex" plugin to overcome this problem. 
https://www.gitbook.com/blog/features/katex. After that, math is rendered in PDF output.

**Comment by dkotrada** [comment]
It doesn't render even on gitbook https://www.gitbook.com/book/dkotrada/testbook/details

**Comment by SamyPesse** [comment]
@dkotrada You need to enable the `mathjax` plugin (or `katex`): http://help.gitbook.com/content/how-can-i-add-plugin.html

**Comment by dkotrada** [comment]
Thank you. Gitbook is Awesome
